# Generated by scripts/homebrew-formula.sh in Kodade/kodade-cli; do not edit by hand.
class KodadeCli < Formula
  desc "Terminal workspace for agent CLIs: workspaces, tabs, panes, agent-state awareness"
  homepage "https://github.com/Kodade/kodade-cli"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/Kodade/kodade-cli/releases/download/v0.1.0/kodade-cli-0.1.0-aarch64-apple-darwin.tar.gz"
      sha256 "bf3bef05db6fa89b19e21e311fd51639ff1d2d876990b6cf26ded5103033c784"
    end
    on_intel do
      url "https://github.com/Kodade/kodade-cli/releases/download/v0.1.0/kodade-cli-0.1.0-x86_64-apple-darwin.tar.gz"
      sha256 "0f630a4069eea7c90ebfb05800636b57d31f2a5552062c494f456b71fc07260a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Kodade/kodade-cli/releases/download/v0.1.0/kodade-cli-0.1.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "b74587ada0342e693dc73bc34562ad0bac5e066f7b02bb3273c9c081c87d3db8"
    end
    on_intel do
      url "https://github.com/Kodade/kodade-cli/releases/download/v0.1.0/kodade-cli-0.1.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "04808f90b27f40b53d9aef134221f50d5db8eab364c79b752cd5c7dc43018adc"
    end
  end

  def install
    bin.install "kodade-cli"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/kodade-cli --version")
  end
end
