# Generated by scripts/homebrew-formula.sh in Kodade/kodade-cli; do not edit by hand.
class KodadeCli < Formula
  desc "Terminal workspace for agent CLIs: workspaces, tabs, panes, agent-state awareness"
  homepage "https://github.com/Kodade/kodade-cli"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/Kodade/kodade-cli/releases/download/v0.2.0/kodade-cli-0.2.0-aarch64-apple-darwin.tar.gz"
      sha256 "cf4adaae2abf7e317671c27790d6a20a00663b7bc45d4f88444b0bc48478b155"
    end
    on_intel do
      url "https://github.com/Kodade/kodade-cli/releases/download/v0.2.0/kodade-cli-0.2.0-x86_64-apple-darwin.tar.gz"
      sha256 "6b80e4ba65c1a46175b295be62f6e52209b04cad476726686996f030512bff85"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Kodade/kodade-cli/releases/download/v0.2.0/kodade-cli-0.2.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "95daee0ce4eca2182c948cb2d5d7b28e458c4c5f9ac9d6ec0d0ca7e27fb32038"
    end
    on_intel do
      url "https://github.com/Kodade/kodade-cli/releases/download/v0.2.0/kodade-cli-0.2.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "d79355a0d3be47fdd2a84d2bcb065fafac45eba5f702885beb0113a072c91d4c"
    end
  end

  def install
    bin.install "kodade-cli"
    generate_completions_from_executable(bin/"kodade-cli", "completion")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/kodade-cli --version")
  end
end
